### ISSUE TITLE
NEEDS A README!!!

### ISSUE THREAD

**Issue by csengineer13** [cfdrake/boombox#1]
CFD, how am I supposed to silently watch from the shadows if I don't know what you're working on? Seriously, the name of this repo is cool, but it would be cooler if I knew what it's aim was.

If you would like, I can guess it's purpose, fork, and create a PR for the readme?

**Comment by cfdrake** [comment]
Dammit, Danny :smile:

Actually started writing one yesterday but haven't committed. I'll keep you posted.

Filing issue under "Annoyances" and closing :wink:

**Comment by cfdrake** [comment]
Fixed by commit 48bcefa, Mr. Brown. Enjoy.

**Comment by csengineer13** [comment]
:+1:
